_data/conf.yml, _data/emergency.yml, conduct/index.html, general-info/social/diy.html, general-info/venues/hotel.html
Adding info from the UM proposal doc:
* Basic safety info and resource links
* Transportation info
* DIY social activity ideas/links
Closes #1
=> Transit, safety, and social activities

_data/conf.yml, general-info/venues/dinner.html, general-info/venues/index.html
- better display when Newcomer's Dinner date isn't known
- hide Game Night for now
=> Two changes on general-info/venues

general-info/venues/index.html, general-info/venues/land.html
I made a couple small edits, to say LPC instead of proposal committee and make one link better for screenreaders, but mostly copied straight from the proposal.
=> add land acknowledgement from proposal

_data/conf.yml
This PR adds the 2024 one-pager PDF to the prospectus page.
After approval, please merge this PR ASAP so we can begin our sponsorship outreach! Thank you!
=> Add One-pager PDF to Prospectus

prospectus/index.html
This PR updates the prospectus to increase the number of DAI sponsorship opportunities available.
Changes include increasing the number of opportunities to:
- 2 - Captioning Sponsor
- 2 - Post-Conference Video Production Sponsor
- 10 - Diversity Scholarships
=> Update Prospectus Numbers

_data/conf.yml
This PR enables the Prospectus button on the site's home page. It's happening, y'all! 🎉
=> Enable the Prospectus button on home page

_data/conf.yml
Do not merge until 10/17/2023
Closes #11
=> Opening keynote nominations

_data/conf.yml
**Do not merge until 11/10/2023**
=> Closing talk voting

_data/conf.yml
**Do not merge until 10/17/2023**
=> Close keynote nominations

_data/conf.yml
**Do not merge until 12/21/2023**
=> Close keynote voting

_data/conf.yml, general-info/scholarships.html
updates for scholarship page 
Really not sure about expected data types of date fields, so I just created them as strings.
Closes #35
=> Updates for Scholarship page

_data/speakers.yml, _posts/2024-05-13-re-thinking-digital-infrastructure-centering-humans-in-integrated-systems-work.md
=> Add Jody Fagan as speaker

prospectus/index.html
=> Marked exhibitor tables as sold out

_data/day1-menus.yml, _data/day2-menus.yml, _data/day3-menus.yml, _data/schedule.yml, _includes/menu.html
Per Kathy Azevedo comment in Slack https://code4lib.slack.com/archives/C0D9KS1EU/p1715182071842359
=> Add food menus and connect to schedule

_data/day1-menus.yml, _data/day2-menus.yml, _data/day3-menus.yml
=> Edits to food

_data/speakers.yml
oh hey, I got promoted since I submitted this proposal 🎉
=> Update Yelton job title

_posts/2024-05-14-An-ArchivematicaPowered-Digital-Preservation-System-for-the-General-Public.md, _posts/2024-05-14-Automating-FAST-subject-heading-assignment-in-the-repository--some-initial-challenges.md, _posts/2024-05-14-Beyond-DSpace-DSpaceCRIS--DSpaceGLAM-as-extended-datamodels.md, _posts/2024-05-14-Building-an-open-source-singlesearch-discovery-implementation.md, _posts/2024-05-14-Case-Study-Jr-How-Digital-Preservation-System-Designs-Can-Impact-Workflows.md, _posts/2024-05-14-Code4Bib-Using-APIs-to-identify-publications-that-analyze-research-data-held-in-a-large-social-science-domain-repository.md, _posts/2024-05-14-Designing-Digital-Directives.md, _posts/2024-05-14-Designing-a-Flexible-StandardsAdherent-Date-Field-for-Novices-and-Professionals.md, _posts/2024-05-14-Designing-an-opensource-application-to-record-Library-Door-Traffic-Counter.md, _posts/2024-05-14-Exploring-Subject-Analysis-with-Annif-Testing-a-Machine-Learning-Tool-for-Subject-Heading-Creation.md, _posts/2024-05-14-From-Screenly-to-OPACs-and-more-Putting-Idle-Raspberry-Pis-to-Work.md, _posts/2024-05-14-Making-the-website-of-a-cashstrapped-academic-library-work-lessons-on-LibGuides.md, _posts/2024-05-14-Observability-in-Library-Technology.md, _posts/2024-05-14-Programmatically-Processing-OCLC-Cross-Reference-Files.md, _posts/2024-05-14-Streamlining-Web-Security-Embracing-Lets-Encrypt-SSL-Certificates-for-HassleFree-Automated-Renewals.md, _posts/2024-05-14-Where-should-I-study-How-to-help-students-discover-and-access-the-right-library-study-spaces-for-their-needs.md
Remove extra bullet points to remove repeating inaccurate presenter name. 
(Jody's name keeps appearing four times in Observability in Library Technology poster for example.)
=> Update poster presentation metadata to fix presenter list

_data/schedule.yml, _includes/presentation_timeline.html
* adding breakout/lightning talk info in schedule.yml
* displaying in the schedule inline
Fixes #75
=> Adding breakouts and lightning talks to the schedule

_posts/2024-05-16-What-You-Can-Do-With-Word-Counts-Learning-the-Basics-of-Text-Analysis-with-Constellate.md
Update 2024-05-16-What-You-Can-Do-With-Word-Counts-Learning-the-Basics-of-Text-Analysis-with-Constellate.md
Jesse Johnston had contacted us this evening saying that due to a schedule conflict, the room is changing to 1255!
=> Update workshop room number

_data/conf.yml, _data/post-conference.yml, index.html
=> Moves website to post-conference existence
